# Generated by Django 4.0.1 on 2022-01-18 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financiall', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Despesas',
            new_name='Despesa',
        ),
        migrations.RenameModel(
            old_name='Receitas',
            new_name='Receita',
        ),
    ]
